# on:
#   push:
#     tags:
#       - "v*"

# jobs:

#   build-and-push-docker:
#     runs-on: ubuntu-latest

#     permissions:
#       contents: read
#       packages: write

#   steps:
#     - name: Checkout
#       uses: actions/checkout@v6

#     - name: Login to GHCR
#       run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

#     - name: Build Docker image
#       run: docker build -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} .

#     - name: Push Docker image
#       run: docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6

  #     - uses: actions/setup-node@v6
  #       with:
  #         node-version: 24

  #     - name: Install
  #       run: npm ci

  #     - name: Build
  #       run: npm run build

  #     - name: config SSH
  #       run: |
  #         mkdir -p ~/.ssh
  #         echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
  #         chmod 600 ~/.ssh/id_rsa
  #         ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

  #     - name: Deploy SSH
  #       run: |
  #         ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
  #           cd /home/azureuser/production/next-cda25 &&
  #           git pull origin main &&
  #           npm ci &&
  #           npm run build &&
  #           pm2 restart app-prod || PORT=30000 pm2 start npm --name app-prod -- start
  #         "