on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Audit des dépendances
        run: npm audit --audit-level=high

      - name: Build
        run: npm run build

      - name: Cache node modules
        uses: actions/cache/save@v5
        with:
          path: |
            node_modules
            .next
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, edge]

    needs: build
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Récupération du cache
        uses: actions/cache/restore@v5
        with:
          path: |
            node_modules
            .next
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - uses: cypress-io/github-action@v7
        with:
          install: false
          start: npm run start
          wait-on: http://localhost:3000
          browser: ${{ matrix.browser }}
      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{ matrix.browser }}
          path: cypress/videos

      - name: Upload Cypress screenshots (only on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots